// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTyxs6cZKUbN7ejmYk_rLVxNg5wVKoSlQ',
    appId: '1:269493681863:web:8fd57be234710be222c8e2',
    messagingSenderId: '269493681863',
    projectId: 'strength-design',
    authDomain: 'strength-design.firebaseapp.com',
    storageBucket: 'strength-design.firebasestorage.app',
    measurementId: 'G-7ZNDWW0Q75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlOjfWQ5qahIdo2qTGRvSIcbQrCkCJjQ',
    appId: '1:269493681863:android:08c89b6201413a4d22c8e2',
    messagingSenderId: '269493681863',
    projectId: 'strength-design',
    storageBucket: 'strength-design.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA-nm6ILavy9i76qj5rM6InJbelzsgm74',
    appId: '1:269493681863:ios:30dceb0220a3955822c8e2',
    messagingSenderId: '269493681863',
    projectId: 'strength-design',
    storageBucket: 'strength-design.firebasestorage.app',
    iosClientId: '269493681863-4f0lvktndgktp2r8udn5davk2tu5rkpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA-nm6ILavy9i76qj5rM6InJbelzsgm74',
    appId: '1:269493681863:ios:30dceb0220a3955822c8e2',
    messagingSenderId: '269493681863',
    projectId: 'strength-design',
    storageBucket: 'strength-design.firebasestorage.app',
    iosClientId: '269493681863-4f0lvktndgktp2r8udn5davk2tu5rkpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTyxs6cZKUbN7ejmYk_rLVxNg5wVKoSlQ',
    appId: '1:269493681863:web:9a070a7abfae854522c8e2',
    messagingSenderId: '269493681863',
    projectId: 'strength-design',
    authDomain: 'strength-design.firebaseapp.com',
    storageBucket: 'strength-design.firebasestorage.app',
    measurementId: 'G-BEKDWMH2LW',
  );
}
